//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opligatorisk_opgave_1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanInformation()
        {
            this.SpecificComponents = new HashSet<SpecificComponents>();
        }
    
        public int LoanId { get; set; }
        public System.DateTime LoanDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string LoaneeName { get; set; }
        public string LoaneeEmail { get; set; }
        public int IsEmailSent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecificComponents> SpecificComponents { get; set; }
    }
}
