//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opligatorisk_opgave_1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificComponents
    {
        public int SpecCompId { get; set; }
        public int ComponentId { get; set; }
        public Nullable<int> LoanedOut { get; set; }
    
        public virtual Components Components { get; set; }
        public virtual LoanInformation LoanInformation { get; set; }
    }
}
